### PR TITLE
101360678 brayden

### PR DESCRIPTION
**Pull request by b-archerr**
###Description
### Checklist before requesting a review

- [] I have performed a self-review of my code.
- []

### CODE REVIEW

**Comment by AnikaShaikh** [comment]
Hello. Sorry, I didn’t notice your Thursday mail and Thank you so much for completing your tasks. Also, I will be glad if you just put your info in README.md file. There are just names rn in the file but I’ll update it later on. Thank you.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by b-archerr** [comment]
It's no problem. I apologize for reaching out so late but thank you for being so understanding regardless. All my tasks are completed, and I have updated my README.md file. It should be updated under my branch (101360678-Brayden) all I did was add my name

If anything else, please let me know. Thank you again and have a great weekend

Brayden Nieto
101360678
________________________________

**Comment by AnikaShaikh** [comment]
Hello. Will you send me your screenshots..?
Actually, we don’t have to upload files individually. I would be glad if you remove the submitted file from bb. Thank youuu. Have a great weekend.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by b-archerr** [comment]
Hello,
I don't see anywhere that we have to submit under one word document as a group. Does my submission stop you from submitting your own individual word doc?
On another note, I cannot remove a submission. In the instance where we have to submit everything under one word document, you can send me everyone's screenshots and I can just overwrite my past submission. This can count as a "group submission"

Any other questions please let me know

Thank you,
Brayden Nieto
101360678
________________________________

**Pull request merged**
